<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>For Ilya</title>
    <link rel="stylesheet" href="./css/styles.css">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></script>   
</head>
<body>
    <header class="header">
        <div class="header__logo">Пассворк</div>
        <div class="header__title">Коробочная демо-версия</div>
    </header>
    <div class="content">
        <div class="form" ng-app="myApp" ng-controller="myCtrl">
            <div class="form__header">Демо-версия коробочной версии Пассворк</div>
            <div class="form__text">Вы можете протестировать основные функции Пассворк на наших серверах.<br>
            <br>Если вы хотите протестировать Пассворк на своем сервере, используйте <span class="form__text_blue">Docker</span>. Инструкцию по установке мы отправили вам в письме. Полноценная версия Пассворк устанавливается без Docker.</div>
            <input type="button" value="Войти" ng-click="sendAjax()">
        </div>
    </div>
    <footer class="footer">
        <div class="footer__copyright">© Passwork 2014–2018</div>
        <div class="footer__contact">info@passwork.me</div>
    </footer>
    <script src="./js/app.js"></script>
</body>
</html>